### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [isiah18/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by isiah18** [comment]
Hey Marco, I figured out the meta tag. I just added the following line to my application.html.erb file in the <head> section above my <title> tag:
 <meta name="viewport" content="width=device-width, initial-scale=1">

I also added this to my master.css.scss file: 
@-ms-viewport{
  width: device-width;
}
I can definitely see the difference when viewing the page on my phone!

**Comment by MarcoMorawec** [comment]
@isiah18 :+1: 

Make sure you close the issue, now that you've added the correct code to it :)
